### PR TITLE
Computed properties

### LINKED ISSUE #200: Computed/TBA fields
# Computed Properties

```json
{
   "id":5,
   "year":2019,
   "realmId":1,
   "auto":[
      {
         "name":"Sandstorm 1",
         "type":"boolean"
      },
      {
         "name":"Sandstorm 2",
         "type":"boolean"
      },
      {
         "name":"Cargo Placed",
         "type":"number"
      },
      {
         "name":"Hatches Placed",
         "type":"number"
      }
   ],
   "teleop":[
      {
         "name":"Cargo Ship Hatches",
         "type":"number"
      },
      {
         "name":"Cargo Ship Cargo",
         "type":"number"
      },
      {
         "name":"Rocket Hatches Lvl 1",
         "type":"number"
      },
      {
         "name":"Rocket Cargo Lvl 1",
         "type":"number"
      },
      {
         "name":"Rocket Hatches Lvl 2",
         "type":"number"
      },
      {
         "name":"Rocket Cargo Lvl 2",
         "type":"number"
      },
      {
         "name":"Rocket Hatches Lvl 3",
         "type":"number"
      },
      {
         "name":"Rocket Cargo Lvl 3",
         "type":"number"
      },
      {
         "name":"Total Rocket Cargo",
         "type":"number",
         "sum": ["Rocket Cargo Lvl 1", "Rocket Cargo Lvl 2", "Rocket Cargo Lvl 3"],
      },
      {
         "name":"Total Rocket Hatches",
         "type":"number",
         "sum": ["Rocket Hatches Lvl 1", "Rocket Hatches Lvl 2", "Rocket Hatches Lvl 3"],
      },
      {
         "name":"Total Cargo",
         "type":"number",
         "sum":["Total Rocket Cargo", "Cargo Ship Cargo"],
      },
      {
         "name":"Total Hatches",
         "type":"number",
         "sum":[
           {
             "tba": "Total Rocket Hatches"
           },
           {
             "field": "Cargo Ship Hatches"
           }
         ],
      },
      {
         "name":"Climbed Lvl 2",
         "type":"boolean",
         "anyOf": [
           {
             "tba": "endgameRobot{{ robotIndex }}", // or
             "field": "endgame",
             "equals": "HabLevel1" // can be string, number, boolean
           },
           {
             "tba": "endgameRobot{{ robotIndex }}", // or
             "field": "endgame",
             "equals": "HabLevel2", // can be string, number, boolean
           }
         ]
      },
      {
         "name":"Climbed Lvl 2",
         "type":"boolean"
      },
      {
         "name":"Climbed Lvl 3",
         "type":"boolean"
      },
      {
         "name":"Assisted Climb Points",
         "type":"number"
      }
   ]
}
```

```json
[
  {
    "team": "frc2733",
    "auto": {
      "statName": {
        "max": 10,
        "avg": 4.25,
        "type": "number"
      }
    },
    "teleop": {
      "statName": {
        "max": 10,
        "avg": 4.25,
        "type": "number"
      }
    }
  }
]
```

### PR DESCRIPTION
**Pull request by fharding1**
# Goal
Closes #200

# Testing

### CODE REVIEW

**Comment by calebeby** [comment]
Frank: Pushes commit

Me: :eyes: :eyes: :eyes:

**Comment by fharding1** [comment]
🙃

**Comment by fharding1** [comment]
Wish I had more time for this

**Comment by fharding1** [comment]
TODO: sort the schema based on dependencies (e.g. if a computed property depends on two non-computed properties place it after them, if a computed property depends on a computed property place it after that computed property)
TODO: actually test that the results it's spitting out are right

**Comment by fharding1** [comment]
Note to self: anyofs with computed property refs aren't working as intended

**Pull request merged**
